method: random

metric:
    name: loss
    goal: maximize
     
parameters:
    
    savepath:
        value: "/dipc_storage/dlopez/Projects/SBI-baccoemu/wandb_models"
    
    training_batch_size:
        distribution: q_log_uniform_values
        max: 256
        min: 16
        q: 8

    learning_rate:
        distribution: q_log_uniform_values
        max: 1e-3
        min: 1e-5
        q: 1e-05
    
    num_hidden_features:
        distribution: q_log_uniform_values
        max: 128
        min: 32
        q: 8
    
    num_transforms:
        distribution: int_uniform
        max: 10
        min: 3
    
    num_blocks:
        distribution: int_uniform
        max: 5
        min: 2
